import {
  Asset,
  Threat,
  Vulnerability,
  SecurityControl,
  CyberRisk,
  ComplianceControl,
  RiskSnapshot,
  Scenario,
} from './types';
import { calculateNormalizedRiskScore, calculateEAL } from './riskEngine';

export const ORGANIZATION_INFO = {
  name: 'Titan Financial Group',
  shortName: 'OptiRisk',
  regulatoryBody: 'Reserve Bank of India (RBI)',
  annualBudget: 1000000, // ₹10,00,000
  currency: 'INR',
  environment: 'PRODUCTION (TIER-1 BANKING CLUSTER)',
  fiscalYear: 'FY 2026-2027',
  totalAssetsValuation: 2450000000, // ₹245 Crore
};

// ==========================================
// 1. ASSETS (16 Assets)
// ==========================================
export const SEED_ASSETS: Asset[] = [
  {
    id: 'asset_mobile_bank',
    name: 'Mobile Banking (TitanPay iOS & Android)',
    type: 'Application',
    criticality: 'Critical',
    criticalityScore: 5,
    usersCount: '2.4M Active Customers',
    financialValuation: 450000000,
    currentRiskScore: 78,
    eal: 860000,
    owner: 'Retail Banking Tech',
    department: 'Digital Channels',
    location: 'Mumbai DC / Multi-Region AWS',
    description: 'Primary consumer mobile interface processing 1.2M daily UPI and IMPS transactions.',
    associatedThreatCount: 5,
    vulnerabilityCount: 3,
  },
  {
    id: 'asset_net_bank',
    name: 'Internet Banking Web Portal',
    type: 'Application',
    criticality: 'Critical',
    criticalityScore: 5,
    usersCount: '1.8M Corporate & Retail',
    financialValuation: 380000000,
    currentRiskScore: 74,
    eal: 720000,
    owner: 'Enterprise Web Platform',
    department: 'Digital Banking',
    location: 'Mumbai Data Center',
    description: 'Corporate treasury and high-value NEFT/RTGS transaction gateway.',
    associatedThreatCount: 4,
    vulnerabilityCount: 4,
  },
  {
    id: 'asset_api_gateway',
    name: 'Core Banking API Gateway (Kong/Apigee)',
    type: 'Infrastructure',
    criticality: 'Critical',
    criticalityScore: 5,
    usersCount: '180 Connected Partners',
    financialValuation: 550000000,
    currentRiskScore: 84,
    eal: 980000,
    owner: 'Integration & Middleware',
    department: 'Core Architecture',
    location: 'Mumbai DC & Bengaluru DR',
    description: 'Central microservices API bus linking fintech partners, account aggregators, and credit bureaus.',
    associatedThreatCount: 6,
    vulnerabilityCount: 5,
  },
  {
    id: 'asset_atm_network',
    name: 'Nationwide ATM Switch & Terminal Fleet',
    type: 'Infrastructure',
    criticality: 'High',
    criticalityScore: 4,
    usersCount: '1,420 ATM Kiosks',
    financialValuation: 220000000,
    currentRiskScore: 68,
    eal: 380000,
    owner: 'ATM Operations',
    department: 'Branch Network & Physical Tech',
    location: 'Pan-India Fleet',
    description: 'Cash dispensing terminals running locked-down Windows Embedded with hardware HSMs.',
    associatedThreatCount: 3,
    vulnerabilityCount: 2,
  },
  {
    id: 'asset_cloud_infra',
    name: 'Cloud Production VPC (AWS & Azure Hybrid)',
    type: 'Cloud',
    criticality: 'Critical',
    criticalityScore: 5,
    usersCount: '45 Internal Cloud Services',
    financialValuation: 310000000,
    currentRiskScore: 72,
    eal: 440000,
    owner: 'Cloud Platform Engineering',
    department: 'Infrastructure & DevOps',
    location: 'AWS ap-south-1 (Mumbai) & Azure India Central',
    description: 'Elastic compute, EKS Kubernetes clusters, and customer analytical data lakes.',
    associatedThreatCount: 4,
    vulnerabilityCount: 4,
  },
  {
    id: 'asset_employee_endpoints',
    name: 'Corporate Employee Fleet (Laptops & Desktops)',
    type: 'Endpoint',
    criticality: 'Medium',
    criticalityScore: 3,
    usersCount: '4,800 Corporate Staff',
    financialValuation: 90000000,
    currentRiskScore: 56,
    eal: 160000,
    owner: 'End User Computing',
    department: 'Enterprise IT',
    location: 'HQ & 180 Branch Offices',
    description: 'Corporate managed Windows 11 and macOS devices used by bank tellers, loan officers, and HQ staff.',
    associatedThreatCount: 4,
    vulnerabilityCount: 3,
  },
  {
    id: 'asset_swift_gateway',
    name: 'SWIFT International Payment Gateway',
    type: 'Application',
    criticality: 'Critical',
    criticalityScore: 5,
    usersCount: 'International Wire Desk',
    financialValuation: 600000000,
    currentRiskScore: 62,
    eal: 290000,
    owner: 'Treasury & Forex Ops',
    department: 'Wholesale Banking',
    location: 'Secure Tier-4 Vault Mumbai',
    description: 'Cross-border interbank messaging interface processing foreign remittances and letters of credit.',
    associatedThreatCount: 2,
    vulnerabilityCount: 1,
  },
  {
    id: 'asset_core_db',
    name: 'Core Oracle Exadata Banking Mainframe',
    type: 'Database',
    criticality: 'Critical',
    criticalityScore: 5,
    usersCount: 'Complete Ledger',
    financialValuation: 850000000,
    currentRiskScore: 59,
    eal: 220000,
    owner: 'Database Administration',
    department: 'Core Banking Solutions',
    location: 'Mumbai Primary Data Center',
    description: 'Authoritative transaction ledger maintaining customer deposits, loan balances, and interest records.',
    associatedThreatCount: 3,
    vulnerabilityCount: 2,
  },
  {
    id: 'asset_iam_dir',
    name: 'Customer & Staff Identity Provider (Okta & Entra ID)',
    type: 'Application',
    criticality: 'Critical',
    criticalityScore: 5,
    usersCount: '4.2M Identities',
    financialValuation: 240000000,
    currentRiskScore: 71,
    eal: 310000,
    owner: 'IAM Security Team',
    department: 'Information Security Office',
    location: 'Multi-Cloud High Availability',
    description: 'OAuth 2.0, OpenID Connect, and SAML identity directory enforcing MFA and RBAC.',
    associatedThreatCount: 4,
    vulnerabilityCount: 3,
  },
  {
    id: 'asset_payment_switch',
    name: 'NPCI UPI & IMPS Real-Time Switch',
    type: 'Infrastructure',
    criticality: 'Critical',
    criticalityScore: 5,
    usersCount: 'High Volume Switch',
    financialValuation: 400000000,
    currentRiskScore: 66,
    eal: 210000,
    owner: 'Payments & Settlement Desk',
    department: 'Payment Systems',
    location: 'Bengaluru Operations Center',
    description: 'Sub-second switch communicating with the National Payments Corporation of India (NPCI).',
    associatedThreatCount: 3,
    vulnerabilityCount: 2,
  },
  {
    id: 'asset_cicd_pipe',
    name: 'DevSecOps GitHub Enterprise & Jenkins CI/CD',
    type: 'Infrastructure',
    criticality: 'High',
    criticalityScore: 4,
    usersCount: '340 Software Engineers',
    financialValuation: 75000000,
    currentRiskScore: 61,
    eal: 140000,
    owner: 'Release Engineering',
    department: 'IT Operations',
    location: 'AWS Private VPC',
    description: 'Automated software build pipelines, container registries, and deployment runners.',
    associatedThreatCount: 3,
    vulnerabilityCount: 2,
  },
  {
    id: 'asset_vendor_portal',
    name: 'Third-Party Vendor Procurement & Settlement Portal',
    type: 'Third-Party',
    criticality: 'High',
    criticalityScore: 4,
    usersCount: '420 External Suppliers',
    financialValuation: 85000000,
    currentRiskScore: 69,
    eal: 190000,
    owner: 'Procurement Operations',
    department: 'Vendor Risk Management',
    location: 'DMZ Public Zone',
    description: 'Supplier invoices, vendor contracts, and outsourcing partner integration points.',
    associatedThreatCount: 4,
    vulnerabilityCount: 3,
  },
  {
    id: 'asset_branch_routers',
    name: 'SD-WAN Edge Branch Routers',
    type: 'Infrastructure',
    criticality: 'Medium',
    criticalityScore: 3,
    usersCount: '180 Branches',
    financialValuation: 50000000,
    currentRiskScore: 52,
    eal: 90000,
    owner: 'Network Engineering',
    department: 'Telecommunications',
    location: 'Pan-India Branches',
    description: 'Edge Cisco & Fortinet routers routing branch banking teller traffic over encrypted IPsec.',
    associatedThreatCount: 2,
    vulnerabilityCount: 2,
  },
  {
    id: 'asset_bi_analytics',
    name: 'Enterprise Big Data & Risk Analytics Lake',
    type: 'Database',
    criticality: 'High',
    criticalityScore: 4,
    usersCount: '80 Data Scientists & Actuaries',
    financialValuation: 110000000,
    currentRiskScore: 57,
    eal: 110000,
    owner: 'Enterprise Data Office',
    department: 'Credit Risk Analytics',
    location: 'Snowflake on AWS',
    description: 'Historical credit scoring, AML compliance models, and fraud detection behavioral data.',
    associatedThreatCount: 2,
    vulnerabilityCount: 2,
  },
  {
    id: 'asset_email_collab',
    name: 'Corporate Microsoft 365 Cloud Suite',
    type: 'Cloud',
    criticality: 'Medium',
    criticalityScore: 3,
    usersCount: '5,200 Mailboxes',
    financialValuation: 60000000,
    currentRiskScore: 58,
    eal: 120000,
    owner: 'IT Collaboration Services',
    department: 'Corporate IT',
    location: 'Microsoft Cloud India',
    description: 'Corporate Exchange email, SharePoint financial records, and Teams executive comms.',
    associatedThreatCount: 3,
    vulnerabilityCount: 2,
  },
  {
    id: 'asset_loan_origination',
    name: 'Digital Retail Loan Origination System (LOS)',
    type: 'Application',
    criticality: 'High',
    criticalityScore: 4,
    usersCount: '45K Loan Applicants / Month',
    financialValuation: 160000000,
    currentRiskScore: 63,
    eal: 150000,
    owner: 'Lending Technology',
    department: 'Retail Assets',
    location: 'Mumbai Data Center',
    description: 'Instant e-KYC verification, credit bureau scoring, and digital loan agreement execution.',
    associatedThreatCount: 2,
    vulnerabilityCount: 1,
  },
];

// ==========================================
// 2. SECURITY CONTROLS CATALOG (12 Controls)
// ==========================================
export const SEED_CONTROLS: SecurityControl[] = [
  {
    id: 'ctrl_api_sec',
    name: 'API Security & WAAP Shield',
    category: 'Application Protection',
    currentMaturity: 2,
    targetMaturity: 4,
    currentInvestment: 150000, // ₹1.5L
    recommendedInvestment: 350000, // ₹3.5L (High priority recommendation)
    maxRiskReductionPct: 38,
    saturationBudget: 500000,
    diminishingCoeff: 0.55,
    coveragePercentage: 62,
    effectivenessScore: 68,
    associatedAssetIds: ['asset_api_gateway', 'asset_mobile_bank', 'asset_payment_switch'],
    description: 'Deep packet inspection for REST/GraphQL APIs, behavioral rate limiting, BOLA/BFLA protection, and OAuth token validation.',
    nistRef: 'PR.PT-3 (Access Protection)',
    isoRef: 'A.8.26 (Application Security)',
    rbiRef: 'Sec 4.2 (API Governance & Security Standards)',
  },
  {
    id: 'ctrl_iam',
    name: 'Identity & Access Management (IAM / PAM)',
    category: 'Identity Governance',
    currentMaturity: 3,
    targetMaturity: 5,
    currentInvestment: 100000, // ₹1.0L
    recommendedInvestment: 175000, // ₹1.75L
    maxRiskReductionPct: 35,
    saturationBudget: 350000,
    diminishingCoeff: 0.62,
    coveragePercentage: 78,
    effectivenessScore: 74,
    associatedAssetIds: ['asset_iam_dir', 'asset_core_db', 'asset_swift_gateway'],
    description: 'Privileged Access Management (PAM), automated session recording, just-in-time credential checkout, and least-privilege RBAC.',
    nistRef: 'PR.AC-4 (Least Privilege)',
    isoRef: 'A.9.2 (User Access Provisioning)',
    rbiRef: 'Sec 3.1 (Access Control & Privilege Governance)',
  },
  {
    id: 'ctrl_edr',
    name: 'Endpoint Detection & Response (EDR / XDR)',
    category: 'Endpoint Security',
    currentMaturity: 4,
    targetMaturity: 5,
    currentInvestment: 200000, // ₹2.0L
    recommendedInvestment: 125000, // Reallocate part to API Security!
    maxRiskReductionPct: 30,
    saturationBudget: 250000,
    diminishingCoeff: 0.85,
    coveragePercentage: 94,
    effectivenessScore: 88,
    associatedAssetIds: ['asset_employee_endpoints', 'asset_branch_routers'],
    description: 'Continuous kernel-level behavioral monitoring, automated host isolation, pass-the-hash detection, and threat hunting.',
    nistRef: 'DE.CM-4 (Malicious Code Detection)',
    isoRef: 'A.8.7 (Protection Against Malware)',
    rbiRef: 'Sec 5.1 (Endpoint Hardening & Anti-Ransomware)',
  },
  {
    id: 'ctrl_cloud_sec',
    name: 'Cloud Security Posture (CSPM & CWPP)',
    category: 'Cloud Protection',
    currentMaturity: 2,
    targetMaturity: 4,
    currentInvestment: 100000, // ₹1.0L
    recommendedInvestment: 150000, // ₹1.5L
    maxRiskReductionPct: 32,
    saturationBudget: 300000,
    diminishingCoeff: 0.60,
    coveragePercentage: 70,
    effectivenessScore: 72,
    associatedAssetIds: ['asset_cloud_infra', 'asset_cicd_pipe', 'asset_bi_analytics'],
    description: 'Real-time IaC scanning, misconfiguration drift remediation, Kubernetes runtime security, and secret leak detection.',
    nistRef: 'PR.IP-1 (Baseline Configuration)',
    isoRef: 'A.8.8 (Management of Technical Vulnerabilities)',
    rbiRef: 'Sec 6.3 (Cloud Architecture & Tenant Segregation)',
  },
  {
    id: 'ctrl_vuln_mgmt',
    name: 'Vulnerability Management & Risk Prioritization',
    category: 'Threat & Exposure',
    currentMaturity: 3,
    targetMaturity: 4,
    currentInvestment: 150000, // ₹1.5L
    recommendedInvestment: 125000,
    maxRiskReductionPct: 28,
    saturationBudget: 250000,
    diminishingCoeff: 0.68,
    coveragePercentage: 82,
    effectivenessScore: 79,
    associatedAssetIds: ['asset_net_bank', 'asset_mobile_bank', 'asset_atm_network'],
    description: 'Automated continuous vulnerability discovery, CVSS/EPSS exploit prioritization, and SLA patch orchestration.',
    nistRef: 'ID.RA-1 (Vulnerability Identification)',
    isoRef: 'A.8.8 (Vulnerability Management)',
    rbiRef: 'Sec 2.4 (Vulnerability Assessment & Penetration Testing)',
  },
  {
    id: 'ctrl_mfa',
    name: 'FIDO2 Passwordless & Contextual MFA',
    category: 'Identity Governance',
    currentMaturity: 3,
    targetMaturity: 5,
    currentInvestment: 50000,
    recommendedInvestment: 75000,
    maxRiskReductionPct: 25,
    saturationBudget: 150000,
    diminishingCoeff: 0.90,
    coveragePercentage: 86,
    effectivenessScore: 91,
    associatedAssetIds: ['asset_iam_dir', 'asset_net_bank', 'asset_employee_endpoints'],
    description: 'Hardware token FIDO2 WebAuthn keys for administrative access, adaptive risk-based authentication for consumers.',
    nistRef: 'PR.AC-7 (Multi-Factor Authentication)',
    isoRef: 'A.9.4.2 (Secure Log-on)',
    rbiRef: 'Sec 3.3 (Mandatory Two-Factor Authentication)',
  },
  {
    id: 'ctrl_employee_sec',
    name: 'Security Awareness & Phishing Simulation',
    category: 'Human Factor',
    currentMaturity: 2,
    targetMaturity: 4,
    currentInvestment: 50000, // ₹50K
    recommendedInvestment: 50000,
    maxRiskReductionPct: 20,
    saturationBudget: 100000,
    diminishingCoeff: 0.75,
    coveragePercentage: 74,
    effectivenessScore: 65,
    associatedAssetIds: ['asset_employee_endpoints', 'asset_email_collab'],
    description: 'Monthly simulated spear-phishing campaigns, role-specific cybersecurity micro-learning for branch tellers and VIPs.',
    nistRef: 'PR.AT-1 (Personnel Training)',
    isoRef: 'A.7.2.2 (Security Awareness & Training)',
    rbiRef: 'Sec 8.1 (Employee Training & Culture)',
  },
  {
    id: 'ctrl_third_party',
    name: 'Third-Party Risk Management (TPRM)',
    category: 'Supply Chain',
    currentMaturity: 2,
    targetMaturity: 4,
    currentInvestment: 50000, // ₹50K
    recommendedInvestment: 75000,
    maxRiskReductionPct: 24,
    saturationBudget: 150000,
    diminishingCoeff: 0.65,
    coveragePercentage: 58,
    effectivenessScore: 62,
    associatedAssetIds: ['asset_vendor_portal', 'asset_api_gateway'],
    description: 'Continuous external attack surface assessment of 420+ suppliers, compliance verification, and SLA security monitoring.',
    nistRef: 'ID.SC-1 (Supply Chain Risk)',
    isoRef: 'A.15.1 (Supplier Relationships)',
    rbiRef: 'Sec 7.2 (Outsourcing & Third-Party Vendor Oversight)',
  },
  {
    id: 'ctrl_siem',
    name: '24/7 Managed SOC & AI Threat Hunting',
    category: 'Detection & Response',
    currentMaturity: 3,
    targetMaturity: 4,
    currentInvestment: 100000,
    recommendedInvestment: 100000,
    maxRiskReductionPct: 29,
    saturationBudget: 300000,
    diminishingCoeff: 0.70,
    coveragePercentage: 88,
    effectivenessScore: 84,
    associatedAssetIds: ['asset_core_db', 'asset_swift_gateway', 'asset_cloud_infra'],
    description: 'Next-Gen SIEM correlating 35,000 EPS across firewalls, cloud audit logs, and identity systems with 15-min SLA.',
    nistRef: 'DE.AE-1 (Anomaly Detection)',
    isoRef: 'A.8.15 (Logging & Monitoring)',
    rbiRef: 'Sec 1.4 (Cyber Security Operations Centre - C-SOC)',
  },
  {
    id: 'ctrl_dlp',
    name: 'Data Loss Prevention & Cryptographic Vaulting',
    category: 'Data Protection',
    currentMaturity: 2,
    targetMaturity: 4,
    currentInvestment: 50000,
    recommendedInvestment: 50000,
    maxRiskReductionPct: 22,
    saturationBudget: 120000,
    diminishingCoeff: 0.72,
    coveragePercentage: 66,
    effectivenessScore: 70,
    associatedAssetIds: ['asset_core_db', 'asset_bi_analytics', 'asset_net_bank'],
    description: 'PCI-DSS tokenization of account and card numbers, egress boundary inspection, and automated USB block policies.',
    nistRef: 'PR.DS-1 (Data-at-Rest Encryption)',
    isoRef: 'A.8.24 (Use of Cryptography)',
    rbiRef: 'Sec 4.1 (Customer Data Protection & Confidentiality)',
  },
  {
    id: 'ctrl_backup_ransom',
    name: 'Immutable Air-Gapped Backup & Recovery',
    category: 'Resilience',
    currentMaturity: 4,
    targetMaturity: 5,
    currentInvestment: 0,
    recommendedInvestment: 50000,
    maxRiskReductionPct: 35,
    saturationBudget: 200000,
    diminishingCoeff: 0.80,
    coveragePercentage: 92,
    effectivenessScore: 92,
    associatedAssetIds: ['asset_core_db', 'asset_cloud_infra', 'asset_swift_gateway'],
    description: 'WORM (Write Once Read Many) AWS S3 Glacier and physical tape vaults with 2-hour transaction recovery objective (RTO).',
    nistRef: 'RC.RP-1 (Recovery Plan Execution)',
    isoRef: 'A.8.14 (Redundancy & Backup)',
    rbiRef: 'Sec 9.2 (Business Continuity & Disaster Recovery)',
  },
  {
    id: 'ctrl_network_zero_trust',
    name: 'Zero Trust Network Architecture (ZTNA)',
    category: 'Perimeter Defense',
    currentMaturity: 2,
    targetMaturity: 4,
    currentInvestment: 0,
    recommendedInvestment: 25000,
    maxRiskReductionPct: 26,
    saturationBudget: 150000,
    diminishingCoeff: 0.65,
    coveragePercentage: 64,
    effectivenessScore: 78,
    associatedAssetIds: ['asset_branch_routers', 'asset_cloud_infra'],
    description: 'Micro-segmentation eliminating implicit internal network trust across branch routers and cloud VPCs.',
    nistRef: 'PR.AC-5 (Network Segregation)',
    isoRef: 'A.8.20 (Network Security)',
    rbiRef: 'Sec 5.3 (Network Perimeter Defense)',
  },
];

// ==========================================
// 3. THREAT CATALOG (16 Threats)
// ==========================================
export const SEED_THREATS: Threat[] = [
  {
    id: 'thr_api_abuse',
    name: 'BOLA / Broken Object Level API Exploitation',
    category: 'Application Layer',
    severity: 'Critical',
    probability: 0.18,
    potentialFinancialImpact: 32000000, // ₹3.2 Crore
    affectedAssetIds: ['asset_api_gateway', 'asset_mobile_bank'],
    mitreTactic: 'Initial Access (TA0001)',
    mitreTechnique: 'T1190 - Exploit Public-Facing Application',
    recommendedAction: 'Deploy runtime WAAP with object ID schema enforcement and rate limiting',
    activeCampaignCount: 8,
  },
  {
    id: 'thr_cred_stuffing',
    name: 'Automated Credential Stuffing & Account Takeover',
    category: 'Identity',
    severity: 'High',
    probability: 0.24,
    potentialFinancialImpact: 18000000, // ₹1.8 Crore
    affectedAssetIds: ['asset_net_bank', 'asset_mobile_bank'],
    mitreTactic: 'Credential Access (TA0006)',
    mitreTechnique: 'T1110 - Brute Force / Credential Stuffing',
    recommendedAction: 'Enforce CAPTCHA v3 and behavioral device fingerprinting on login routes',
    activeCampaignCount: 14,
  },
  {
    id: 'thr_ransomware',
    name: 'Double-Extortion Ransomware Syndicate',
    category: 'Malware',
    severity: 'Critical',
    probability: 0.08,
    potentialFinancialImpact: 65000000, // ₹6.5 Crore
    affectedAssetIds: ['asset_employee_endpoints', 'asset_core_db', 'asset_cloud_infra'],
    mitreTactic: 'Impact (TA0040)',
    mitreTechnique: 'T1486 - Data Encrypted for Impact',
    recommendedAction: 'Maintain air-gapped immutable backups and aggressive EDR behavior blocking',
    activeCampaignCount: 3,
  },
  {
    id: 'thr_swift_fraud',
    name: 'SWIFT Alliance Access Interbank Hijacking',
    category: 'Financial Fraud',
    severity: 'Critical',
    probability: 0.03,
    potentialFinancialImpact: 120000000, // ₹12.0 Crore
    affectedAssetIds: ['asset_swift_gateway'],
    mitreTactic: 'Impact (TA0040)',
    mitreTechnique: 'T1565 - Data Manipulation / Financial Fraud',
    recommendedAction: 'Enforce dual-custody hardware authorization keys and isolated terminal network',
    activeCampaignCount: 1,
  },
  {
    id: 'thr_cloud_misconfig',
    name: 'Cloud Storage & IAM Permission Misconfiguration',
    category: 'Cloud',
    severity: 'High',
    probability: 0.15,
    potentialFinancialImpact: 22000000, // ₹2.2 Crore
    affectedAssetIds: ['asset_cloud_infra', 'asset_bi_analytics'],
    mitreTactic: 'Defense Evasion (TA0005)',
    mitreTechnique: 'T1530 - Data from Cloud Storage Object',
    recommendedAction: 'Implement continuous CSPM automated drift remediation and IAM least privilege',
    activeCampaignCount: 6,
  },
  {
    id: 'thr_atm_malware',
    name: 'ATM Black-Box Cash-out & Jackpotting',
    category: 'Physical / Hardware',
    severity: 'High',
    probability: 0.06,
    potentialFinancialImpact: 14000000, // ₹1.4 Crore
    affectedAssetIds: ['asset_atm_network'],
    mitreTactic: 'Initial Access (TA0001)',
    mitreTechnique: 'T1200 - Hardware Additions / Physical Access',
    recommendedAction: 'Hardware port disabling, OS integrity verification, and physical top-box tamper alarms',
    activeCampaignCount: 2,
  },
  {
    id: 'thr_supply_chain',
    name: 'Third-Party Software Dependency Poisoning',
    category: 'Supply Chain',
    severity: 'High',
    probability: 0.12,
    potentialFinancialImpact: 19000000, // ₹1.9 Crore
    affectedAssetIds: ['asset_cicd_pipe', 'asset_vendor_portal'],
    mitreTactic: 'Initial Access (TA0001)',
    mitreTechnique: 'T1195 - Supply Chain Compromise',
    recommendedAction: 'Software Bill of Materials (SBOM) verification and automated dependency pinning',
    activeCampaignCount: 4,
  },
  {
    id: 'thr_insider_abuse',
    name: 'Privileged Staff Unauthorized Customer Record Exfiltration',
    category: 'Insider Threat',
    severity: 'Medium',
    probability: 0.10,
    potentialFinancialImpact: 16000000, // ₹1.6 Crore
    affectedAssetIds: ['asset_core_db', 'asset_loan_origination'],
    mitreTactic: 'Exfiltration (TA0010)',
    mitreTechnique: 'T1078 - Valid Accounts / Insider Access',
    recommendedAction: 'PAM video session recording, strict database DLP, and anomaly alerting',
    activeCampaignCount: 1,
  },
  {
    id: 'thr_spear_phish',
    name: 'Executive Spear-Phishing & Business Email Compromise',
    category: 'Social Engineering',
    severity: 'High',
    probability: 0.22,
    potentialFinancialImpact: 11000000, // ₹1.1 Crore
    affectedAssetIds: ['asset_email_collab', 'asset_employee_endpoints'],
    mitreTactic: 'Initial Access (TA0001)',
    mitreTechnique: 'T1566.002 - Spearphishing Link',
    recommendedAction: 'In-line email header spoofing protection (DMARC/DKIM) and phishing awareness',
    activeCampaignCount: 9,
  },
  {
    id: 'thr_ddos_banking',
    name: 'Volumetric L7 DDoS on Mobile & Web Endpoints',
    category: 'Availability',
    severity: 'Medium',
    probability: 0.20,
    potentialFinancialImpact: 9000000, // ₹90 Lakhs
    affectedAssetIds: ['asset_net_bank', 'asset_mobile_bank'],
    mitreTactic: 'Impact (TA0040)',
    mitreTechnique: 'T1498 - Network Denial of Service',
    recommendedAction: 'Cloud scrubbing center with automated SYN-flood mitigation and geo-blocking',
    activeCampaignCount: 5,
  },
  {
    id: 'thr_sim_swap',
    name: 'Targeted Telecom SIM Swap & OTP Interception',
    category: 'Identity / Telco',
    severity: 'Medium',
    probability: 0.14,
    potentialFinancialImpact: 8500000, // ₹85 Lakhs
    affectedAssetIds: ['asset_mobile_bank'],
    mitreTactic: 'Credential Access (TA0006)',
    mitreTechnique: 'T1539 - Steal Web Session / SIM Hijacking',
    recommendedAction: 'Transition from SMS OTP to cryptographic in-app device bound approval tokens',
    activeCampaignCount: 7,
  },
  {
    id: 'thr_pass_the_hash',
    name: 'Lateral Movement via Stolen NTLM Hashes',
    category: 'Network',
    severity: 'Medium',
    probability: 0.11,
    potentialFinancialImpact: 12000000, // ₹1.2 Crore
    affectedAssetIds: ['asset_employee_endpoints', 'asset_branch_routers'],
    mitreTactic: 'Lateral Movement (TA0008)',
    mitreTechnique: 'T1550.002 - Pass the Hash',
    recommendedAction: 'Disable NTLMv1, implement Credential Guard, and restrict admin workstation logins',
    activeCampaignCount: 2,
  },
  {
    id: 'thr_zero_day',
    name: 'Remote Code Execution in Enterprise Web Frameworks',
    category: 'Vulnerability',
    severity: 'Critical',
    probability: 0.05,
    potentialFinancialImpact: 35000000, // ₹3.5 Crore
    affectedAssetIds: ['asset_net_bank', 'asset_api_gateway'],
    mitreTactic: 'Execution (TA0002)',
    mitreTechnique: 'T1059 - Command and Scripting Interpreter',
    recommendedAction: 'Runtime Application Self-Protection (RASP) and aggressive patch SLAs',
    activeCampaignCount: 2,
  },
  {
    id: 'thr_vendor_breach',
    name: 'Downstream Vendor Access Gateway Compromise',
    category: 'Supply Chain',
    severity: 'High',
    probability: 0.16,
    potentialFinancialImpact: 15000000, // ₹1.5 Crore
    affectedAssetIds: ['asset_vendor_portal'],
    mitreTactic: 'Initial Access (TA0001)',
    mitreTechnique: 'T1199 - Trusted Relationship',
    recommendedAction: 'Enforce MFA and zero trust boundary for all third-party external sessions',
    activeCampaignCount: 4,
  },
  {
    id: 'thr_db_injection',
    name: 'Blind SQL Injection in Legacy Reporting Services',
    category: 'Application Layer',
    severity: 'Medium',
    probability: 0.09,
    potentialFinancialImpact: 13000000, // ₹1.3 Crore
    affectedAssetIds: ['asset_loan_origination'],
    mitreTactic: 'Execution (TA0002)',
    mitreTechnique: 'T1059 - SQL Injection',
    recommendedAction: 'Code refactoring with parameterized queries and ORM validation',
    activeCampaignCount: 1,
  },
  {
    id: 'thr_man_in_middle',
    name: 'BGP Route Hijacking & Rogue Certificate Injection',
    category: 'Network',
    severity: 'Low',
    probability: 0.02,
    potentialFinancialImpact: 20000000, // ₹2.0 Crore
    affectedAssetIds: ['asset_branch_routers'],
    mitreTactic: 'Credential Access (TA0006)',
    mitreTechnique: 'T1557 - Adversary-in-the-Middle',
    recommendedAction: 'Deploy RPKI route validation and strict certificate pinning on mobile apps',
    activeCampaignCount: 0,
  },
];

// ==========================================
// 4. VULNERABILITIES (30 CVEs)
// ==========================================
export const SEED_VULNERABILITIES: Vulnerability[] = [
  {
    id: 'CVE-2024-3400',
    title: 'Palo Alto GlobalProtect Command Injection',
    assetId: 'asset_branch_routers',
    assetName: 'SD-WAN Edge Branch Routers',
    severity: 'Critical',
    cvssScore: 10.0,
    exploitability: 'Active Exploit',
    financialExposure: 1800000,
    recommendedControlId: 'ctrl_network_zero_trust',
    status: 'In Progress',
    discoveredDate: '2026-08-12',
    cwe: 'CWE-77: Command Injection',
  },
  {
    id: 'CVE-2024-21413',
    title: 'Microsoft Outlook Moniker Link Remote Code Execution',
    assetId: 'asset_employee_endpoints',
    assetName: 'Corporate Employee Fleet',
    severity: 'Critical',
    cvssScore: 9.8,
    exploitability: 'Active Exploit',
    financialExposure: 2400000,
    recommendedControlId: 'ctrl_edr',
    status: 'Open',
    discoveredDate: '2026-08-19',
    cwe: 'CWE-20: Improper Input Validation',
  },
  {
    id: 'CVE-2024-38021',
    title: 'Microsoft Office Remote Code Execution Zero-Click',
    assetId: 'asset_employee_endpoints',
    assetName: 'Corporate Employee Fleet',
    severity: 'High',
    cvssScore: 8.8,
    exploitability: 'PoC Available',
    financialExposure: 1500000,
    recommendedControlId: 'ctrl_edr',
    status: 'In Progress',
    discoveredDate: '2026-08-25',
    cwe: 'CWE-94: Code Injection',
  },
  {
    id: 'CVE-2024-27198',
    title: 'JetBrains TeamCity Authentication Bypass',
    assetId: 'asset_cicd_pipe',
    assetName: 'DevSecOps GitHub Enterprise & Jenkins CI/CD',
    severity: 'Critical',
    cvssScore: 9.8,
    exploitability: 'Active Exploit',
    financialExposure: 3200000,
    recommendedControlId: 'ctrl_iam',
    status: 'Remediated',
    discoveredDate: '2026-07-15',
    cwe: 'CWE-306: Missing Authentication',
  },
  {
    id: 'CVE-2024-21762',
    title: 'FortiOS Out-of-Bound Write in SSL-VPN',
    assetId: 'asset_branch_routers',
    assetName: 'SD-WAN Edge Branch Routers',
    severity: 'Critical',
    cvssScore: 9.8,
    exploitability: 'Active Exploit',
    financialExposure: 2800000,
    recommendedControlId: 'ctrl_vuln_mgmt',
    status: 'Open',
    discoveredDate: '2026-08-04',
    cwe: 'CWE-787: Out-of-Bounds Write',
  },
  {
    id: 'CVE-2024-43451',
    title: 'Windows NTLM Hash Disclosure Spoofing',
    assetId: 'asset_employee_endpoints',
    assetName: 'Corporate Employee Fleet',
    severity: 'High',
    cvssScore: 8.5,
    exploitability: 'Active Exploit',
    financialExposure: 1900000,
    recommendedControlId: 'ctrl_edr',
    status: 'Open',
    discoveredDate: '2026-08-30',
    cwe: 'CWE-287: Improper Authentication',
  },
  {
    id: 'CVE-2024-23897',
    title: 'Jenkins CLI Arbitrary File Read Vulnerability',
    assetId: 'asset_cicd_pipe',
    assetName: 'DevSecOps GitHub Enterprise & Jenkins CI/CD',
    severity: 'High',
    cvssScore: 8.6,
    exploitability: 'PoC Available',
    financialExposure: 1200000,
    recommendedControlId: 'ctrl_cloud_sec',
    status: 'Remediated',
    discoveredDate: '2026-07-28',
    cwe: 'CWE-22: Path Traversal',
  },
  {
    id: 'CVE-2024-1709',
    title: 'ConnectWise ScreenConnect Authentication Bypass',
    assetId: 'asset_vendor_portal',
    assetName: 'Third-Party Vendor Procurement & Settlement Portal',
    severity: 'Critical',
    cvssScore: 10.0,
    exploitability: 'Active Exploit',
    financialExposure: 3500000,
    recommendedControlId: 'ctrl_third_party',
    status: 'Open',
    discoveredDate: '2026-08-02',
    cwe: 'CWE-288: Auth Bypass Alternate Path',
  },
  {
    id: 'CVE-2024-20353',
    title: 'Cisco Adaptive Security Appliance Web Server DoS',
    assetId: 'asset_atm_network',
    assetName: 'Nationwide ATM Switch & Terminal Fleet',
    severity: 'High',
    cvssScore: 8.6,
    exploitability: 'Theoretical',
    financialExposure: 950000,
    recommendedControlId: 'ctrl_vuln_mgmt',
    status: 'In Progress',
    discoveredDate: '2026-08-14',
    cwe: 'CWE-400: Resource Exhaustion',
  },
  {
    id: 'CVE-2024-29973',
    title: 'Zyxel NAS Command Injection via NGINX URI',
    assetId: 'asset_branch_routers',
    assetName: 'SD-WAN Edge Branch Routers',
    severity: 'High',
    cvssScore: 8.8,
    exploitability: 'PoC Available',
    financialExposure: 800000,
    recommendedControlId: 'ctrl_network_zero_trust',
    status: 'Remediated',
    discoveredDate: '2026-06-20',
    cwe: 'CWE-78: OS Command Injection',
  },
  {
    id: 'CVE-2024-4577',
    title: 'PHP-CGI Windows Argument Injection RCE',
    assetId: 'asset_vendor_portal',
    assetName: 'Third-Party Vendor Procurement & Settlement Portal',
    severity: 'Critical',
    cvssScore: 9.8,
    exploitability: 'Active Exploit',
    financialExposure: 2600000,
    recommendedControlId: 'ctrl_api_sec',
    status: 'Open',
    discoveredDate: '2026-08-11',
    cwe: 'CWE-88: Argument Injection',
  },
  {
    id: 'CVE-2024-6387',
    title: 'OpenSSH regreSSHion Signal Handler Race Condition RCE',
    assetId: 'asset_cloud_infra',
    assetName: 'Cloud Production VPC',
    severity: 'Critical',
    cvssScore: 8.1,
    exploitability: 'PoC Available',
    financialExposure: 4200000,
    recommendedControlId: 'ctrl_cloud_sec',
    status: 'In Progress',
    discoveredDate: '2026-08-01',
    cwe: 'CWE-362: Race Condition',
  },
  {
    id: 'CVE-2024-38856',
    title: 'Apache OFBiz Unauthenticated Remote Code Execution',
    assetId: 'asset_loan_origination',
    assetName: 'Digital Retail Loan Origination System',
    severity: 'Critical',
    cvssScore: 9.8,
    exploitability: 'Active Exploit',
    financialExposure: 3100000,
    recommendedControlId: 'ctrl_vuln_mgmt',
    status: 'Open',
    discoveredDate: '2026-08-18',
    cwe: 'CWE-287: Improper Authentication',
  },
  {
    id: 'CVE-2024-50012',
    title: 'OAuth 2.0 State Parameter Session Fixation in Banking API',
    assetId: 'asset_api_gateway',
    assetName: 'Core Banking API Gateway',
    severity: 'High',
    cvssScore: 8.4,
    exploitability: 'Active Exploit',
    financialExposure: 4800000,
    recommendedControlId: 'ctrl_api_sec',
    status: 'Open',
    discoveredDate: '2026-08-22',
    cwe: 'CWE-384: Session Fixation',
  },
  {
    id: 'CVE-2024-50013',
    title: 'Broken Object Level Authorization (BOLA) in Account Balance API',
    assetId: 'asset_api_gateway',
    assetName: 'Core Banking API Gateway',
    severity: 'Critical',
    cvssScore: 9.4,
    exploitability: 'Active Exploit',
    financialExposure: 6400000,
    recommendedControlId: 'ctrl_api_sec',
    status: 'Open',
    discoveredDate: '2026-08-26',
    cwe: 'CWE-639: Authorization Bypass Through User-Controlled Key',
  },
  {
    id: 'CVE-2024-3094',
    title: 'XZ Utils Backdoor Liblzma Compression Injection',
    assetId: 'asset_cloud_infra',
    assetName: 'Cloud Production VPC',
    severity: 'Critical',
    cvssScore: 10.0,
    exploitability: 'Active Exploit',
    financialExposure: 5000000,
    recommendedControlId: 'ctrl_cloud_sec',
    status: 'Remediated',
    discoveredDate: '2026-04-10',
    cwe: 'CWE-506: Embedded Malicious Code',
  },
  {
    id: 'CVE-2024-24919',
    title: 'Check Point Quantum Security Gateway Information Disclosure',
    assetId: 'asset_branch_routers',
    assetName: 'SD-WAN Edge Branch Routers',
    severity: 'High',
    cvssScore: 8.6,
    exploitability: 'Active Exploit',
    financialExposure: 1700000,
    recommendedControlId: 'ctrl_network_zero_trust',
    status: 'In Progress',
    discoveredDate: '2026-07-29',
    cwe: 'CWE-200: Exposure of Sensitive Information',
  },
  {
    id: 'CVE-2024-26169',
    title: 'Windows Error Reporting Service Privilege Escalation',
    assetId: 'asset_employee_endpoints',
    assetName: 'Corporate Employee Fleet',
    severity: 'High',
    cvssScore: 7.8,
    exploitability: 'Active Exploit',
    financialExposure: 1100000,
    recommendedControlId: 'ctrl_edr',
    status: 'Remediated',
    discoveredDate: '2026-07-12',
    cwe: 'CWE-269: Privilege Management',
  },
  {
    id: 'CVE-2024-38063',
    title: 'Windows TCP/IP Remote Code Execution Vulnerability',
    assetId: 'asset_employee_endpoints',
    assetName: 'Corporate Employee Fleet',
    severity: 'Critical',
    cvssScore: 9.8,
    exploitability: 'PoC Available',
    financialExposure: 2900000,
    recommendedControlId: 'ctrl_edr',
    status: 'In Progress',
    discoveredDate: '2026-08-20',
    cwe: 'CWE-119: Memory Buffer Boundary',
  },
  {
    id: 'CVE-2024-20419',
    title: 'Cisco Smart Software Manager On-Prem Auth Bypass',
    assetId: 'asset_atm_network',
    assetName: 'Nationwide ATM Switch & Terminal Fleet',
    severity: 'Critical',
    cvssScore: 10.0,
    exploitability: 'Active Exploit',
    financialExposure: 2100000,
    recommendedControlId: 'ctrl_iam',
    status: 'Open',
    discoveredDate: '2026-08-09',
    cwe: 'CWE-306: Missing Authentication',
  },
  {
    id: 'CVE-2024-38112',
    title: 'Windows MSHTML Platform Spoofing Vulnerability',
    assetId: 'asset_employee_endpoints',
    assetName: 'Corporate Employee Fleet',
    severity: 'High',
    cvssScore: 7.5,
    exploitability: 'Active Exploit',
    financialExposure: 900000,
    recommendedControlId: 'ctrl_employee_sec',
    status: 'In Progress',
    discoveredDate: '2026-08-16',
    cwe: 'CWE-451: User Interface Spoofing',
  },
  {
    id: 'CVE-2024-50020',
    title: 'Insufficient Rate Limiting on Customer OTP Generation API',
    assetId: 'asset_mobile_bank',
    assetName: 'Mobile Banking (TitanPay)',
    severity: 'High',
    cvssScore: 7.9,
    exploitability: 'Active Exploit',
    financialExposure: 3400000,
    recommendedControlId: 'ctrl_api_sec',
    status: 'Open',
    discoveredDate: '2026-08-28',
    cwe: 'CWE-799: Improper Control of Generation Frequency',
  },
  {
    id: 'CVE-2024-50021',
    title: 'JWT Token Signing Algorithm None Vulnerability in Partner Gateway',
    assetId: 'asset_api_gateway',
    assetName: 'Core Banking API Gateway',
    severity: 'Critical',
    cvssScore: 9.1,
    exploitability: 'PoC Available',
    financialExposure: 5200000,
    recommendedControlId: 'ctrl_api_sec',
    status: 'Open',
    discoveredDate: '2026-08-25',
    cwe: 'CWE-347: Improper Verification of Cryptographic Signature',
  },
  {
    id: 'CVE-2024-28986',
    title: 'SolarWinds Web Help Desk Java Deserialization RCE',
    assetId: 'asset_vendor_portal',
    assetName: 'Third-Party Vendor Procurement & Settlement Portal',
    severity: 'Critical',
    cvssScore: 9.8,
    exploitability: 'Active Exploit',
    financialExposure: 2700000,
    recommendedControlId: 'ctrl_third_party',
    status: 'In Progress',
    discoveredDate: '2026-08-15',
    cwe: 'CWE-502: Deserialization of Untrusted Data',
  },
  {
    id: 'CVE-2024-38200',
    title: 'Microsoft Office Spoofing NTLM Credential Theft',
    assetId: 'asset_employee_endpoints',
    assetName: 'Corporate Employee Fleet',
    severity: 'Medium',
    cvssScore: 6.5,
    exploitability: 'PoC Available',
    financialExposure: 650000,
    recommendedControlId: 'ctrl_edr',
    status: 'Remediated',
    discoveredDate: '2026-08-07',
    cwe: 'CWE-200: Information Exposure',
  },
  {
    id: 'CVE-2024-40711',
    title: 'Veeam Backup & Replication Remote Code Execution',
    assetId: 'asset_core_db',
    assetName: 'Core Oracle Exadata Banking Mainframe',
    severity: 'Critical',
    cvssScore: 9.8,
    exploitability: 'Active Exploit',
    financialExposure: 4900000,
    recommendedControlId: 'ctrl_backup_ransom',
    status: 'Open',
    discoveredDate: '2026-09-02',
    cwe: 'CWE-502: Deserialization of Untrusted Data',
  },
  {
    id: 'CVE-2024-23222',
    title: 'Apple WebKit Memory Corruption in Mobile Banking App View',
    assetId: 'asset_mobile_bank',
    assetName: 'Mobile Banking (TitanPay)',
    severity: 'High',
    cvssScore: 8.8,
    exploitability: 'Active Exploit',
    financialExposure: 2100000,
    recommendedControlId: 'ctrl_vuln_mgmt',
    status: 'In Progress',
    discoveredDate: '2026-07-22',
    cwe: 'CWE-119: Memory Corruption',
  },
  {
    id: 'CVE-2024-50030',
    title: 'AWS S3 Cloud Object Bucket Write ACL Permissive Policy',
    assetId: 'asset_cloud_infra',
    assetName: 'Cloud Production VPC',
    severity: 'Medium',
    cvssScore: 6.8,
    exploitability: 'Theoretical',
    financialExposure: 850000,
    recommendedControlId: 'ctrl_cloud_sec',
    status: 'Open',
    discoveredDate: '2026-08-29',
    cwe: 'CWE-732: Incorrect Permission Assignment',
  },
  {
    id: 'CVE-2024-50031',
    title: 'Lack of Hardware Key Binding on Treasury Terminal Session',
    assetId: 'asset_swift_gateway',
    assetName: 'SWIFT International Payment Gateway',
    severity: 'High',
    cvssScore: 7.9,
    exploitability: 'Theoretical',
    financialExposure: 3900000,
    recommendedControlId: 'ctrl_mfa',
    status: 'In Progress',
    discoveredDate: '2026-08-10',
    cwe: 'CWE-287: Improper Authentication',
  },
  {
    id: 'CVE-2024-50032',
    title: 'Unencrypted Intermediate Ledger Cache in Redis Store',
    assetId: 'asset_payment_switch',
    assetName: 'NPCI UPI & IMPS Real-Time Switch',
    severity: 'Medium',
    cvssScore: 6.2,
    exploitability: 'Theoretical',
    financialExposure: 1100000,
    recommendedControlId: 'ctrl_dlp',
    status: 'Remediated',
    discoveredDate: '2026-07-18',
    cwe: 'CWE-311: Missing Encryption of Sensitive Data',
  },
];

// ==========================================
// 5. CYBER RISKS (26 Quantified Risks)
// ==========================================
export const SEED_RISKS: CyberRisk[] = [
  {
    id: 'risk_01',
    title: 'API Authentication & BOLA Authorization Vulnerability',
    assetId: 'asset_api_gateway',
    assetName: 'Core Banking API Gateway',
    threatId: 'thr_api_abuse',
    threatName: 'BOLA / Broken Object Level API Exploitation',
    vulnerabilityId: 'CVE-2024-50013',
    likelihood: 4,
    impact: 5,
    assetCriticality: 5,
    riskScore: 80,
    severity: 'Critical',
    probabilityOfLoss: 0.12,
    financialImpact: 32000000, // ₹3.2 Crore
    expectedAnnualLoss: 3840000 * 0.22, // ~₹8.4L
    existingControls: ['Basic Web Application Firewall (Rate Limit Only)'],
    recommendedControlId: 'ctrl_api_sec',
    recommendedControlName: 'API Security & WAAP Shield',
    residualRiskScore: 36,
  },
  {
    id: 'risk_02',
    title: 'Privileged Cloud Administrator Account Exposure',
    assetId: 'asset_cloud_infra',
    assetName: 'Cloud Production VPC',
    threatId: 'thr_cloud_misconfig',
    threatName: 'Cloud Storage & IAM Permission Misconfiguration',
    vulnerabilityId: 'CVE-2024-6387',
    likelihood: 3,
    impact: 5,
    assetCriticality: 5,
    riskScore: 75,
    severity: 'Critical',
    probabilityOfLoss: 0.10,
    financialImpact: 22000000,
    expectedAnnualLoss: 3840000 * 0.14, // ~₹5.4L
    existingControls: ['AWS CloudTrail', 'Standard MFA'],
    recommendedControlId: 'ctrl_iam',
    recommendedControlName: 'Identity & Access Management (IAM / PAM)',
    residualRiskScore: 32,
  },
  {
    id: 'risk_03',
    title: 'Ransomware Outbreak on Branch Teller Endpoints',
    assetId: 'asset_employee_endpoints',
    assetName: 'Corporate Employee Fleet',
    threatId: 'thr_ransomware',
    threatName: 'Double-Extortion Ransomware Syndicate',
    vulnerabilityId: 'CVE-2024-21413',
    likelihood: 3,
    impact: 4,
    assetCriticality: 4,
    riskScore: 68,
    severity: 'High',
    probabilityOfLoss: 0.08,
    financialImpact: 35000000,
    expectedAnnualLoss: 3840000 * 0.12, // ~₹4.6L
    existingControls: ['Legacy Antivirus', 'Periodic Windows Update'],
    recommendedControlId: 'ctrl_edr',
    recommendedControlName: 'Endpoint Detection & Response (EDR / XDR)',
    residualRiskScore: 28,
  },
  {
    id: 'risk_04',
    title: 'Credential Stuffing on Internet Banking Login Page',
    assetId: 'asset_net_bank',
    assetName: 'Internet Banking Web Portal',
    threatId: 'thr_cred_stuffing',
    threatName: 'Automated Credential Stuffing & Account Takeover',
    vulnerabilityId: 'CVE-2024-50020',
    likelihood: 4,
    impact: 4,
    assetCriticality: 5,
    riskScore: 72,
    severity: 'High',
    probabilityOfLoss: 0.16,
    financialImpact: 18000000,
    expectedAnnualLoss: 3840000 * 0.11, // ~₹4.2L
    existingControls: ['SMS OTP Verification'],
    recommendedControlId: 'ctrl_mfa',
    recommendedControlName: 'FIDO2 Passwordless & Contextual MFA',
    residualRiskScore: 25,
  },
  {
    id: 'risk_05',
    title: 'Third-Party Vendor Remote Access Software Exploit',
    assetId: 'asset_vendor_portal',
    assetName: 'Third-Party Vendor Procurement & Settlement Portal',
    threatId: 'thr_vendor_breach',
    threatName: 'Downstream Vendor Access Gateway Compromise',
    vulnerabilityId: 'CVE-2024-1709',
    likelihood: 3,
    impact: 4,
    assetCriticality: 4,
    riskScore: 65,
    severity: 'High',
    probabilityOfLoss: 0.14,
    financialImpact: 15000000,
    expectedAnnualLoss: 3840000 * 0.09, // ~₹3.5L
    existingControls: ['Contractual NDA', 'Vendor Questionnaire'],
    recommendedControlId: 'ctrl_third_party',
    recommendedControlName: 'Third-Party Risk Management (TPRM)',
    residualRiskScore: 30,
  },
  {
    id: 'risk_06',
    title: 'Customer Data Extraction via Mobile Reverse Engineering',
    assetId: 'asset_mobile_bank',
    assetName: 'Mobile Banking (TitanPay)',
    threatId: 'thr_api_abuse',
    threatName: 'BOLA / Broken Object Level API Exploitation',
    vulnerabilityId: 'CVE-2024-23222',
    likelihood: 3,
    impact: 4,
    assetCriticality: 5,
    riskScore: 70,
    severity: 'High',
    probabilityOfLoss: 0.10,
    financialImpact: 20000000,
    expectedAnnualLoss: 3840000 * 0.08, // ~₹3.1L
    existingControls: ['Client App ProGuard Obfuscation'],
    recommendedControlId: 'ctrl_api_sec',
    recommendedControlName: 'API Security & WAAP Shield',
    residualRiskScore: 29,
  },
  {
    id: 'risk_07',
    title: 'ATM Edge Gateway SSL-VPN Remote Code Execution',
    assetId: 'asset_atm_network',
    assetName: 'Nationwide ATM Switch & Terminal Fleet',
    threatId: 'thr_atm_malware',
    threatName: 'ATM Black-Box Cash-out & Jackpotting',
    vulnerabilityId: 'CVE-2024-21762',
    likelihood: 2,
    impact: 5,
    assetCriticality: 4,
    riskScore: 64,
    severity: 'High',
    probabilityOfLoss: 0.06,
    financialImpact: 25000000,
    expectedAnnualLoss: 3840000 * 0.06, // ~₹2.3L
    existingControls: ['Hardware Firewall'],
    recommendedControlId: 'ctrl_vuln_mgmt',
    recommendedControlName: 'Vulnerability Management & Risk Prioritization',
    residualRiskScore: 24,
  },
  {
    id: 'risk_08',
    title: 'SWIFT Key Injection via Unpatched Workstation',
    assetId: 'asset_swift_gateway',
    assetName: 'SWIFT International Payment Gateway',
    threatId: 'thr_swift_fraud',
    threatName: 'SWIFT Alliance Access Interbank Hijacking',
    vulnerabilityId: 'CVE-2024-50031',
    likelihood: 1,
    impact: 5,
    assetCriticality: 5,
    riskScore: 60,
    severity: 'Medium',
    probabilityOfLoss: 0.02,
    financialImpact: 100000000,
    expectedAnnualLoss: 3840000 * 0.05, // ~₹1.9L
    existingControls: ['Biometric Room Entry', 'Hardware Smartcards'],
    recommendedControlId: 'ctrl_iam',
    recommendedControlName: 'Identity & Access Management (IAM / PAM)',
    residualRiskScore: 18,
  },
  {
    id: 'risk_09',
    title: 'CI/CD Pipeline Dependency Injection Poisoning',
    assetId: 'asset_cicd_pipe',
    assetName: 'DevSecOps GitHub Enterprise & Jenkins CI/CD',
    threatId: 'thr_supply_chain',
    threatName: 'Third-Party Software Dependency Poisoning',
    vulnerabilityId: 'CVE-2024-27198',
    likelihood: 3,
    impact: 3,
    assetCriticality: 4,
    riskScore: 58,
    severity: 'Medium',
    probabilityOfLoss: 0.09,
    financialImpact: 12000000,
    expectedAnnualLoss: 3840000 * 0.04, // ~₹1.5L
    existingControls: ['Branch Protection Rules'],
    recommendedControlId: 'ctrl_cloud_sec',
    recommendedControlName: 'Cloud Security Posture (CSPM & CWPP)',
    residualRiskScore: 22,
  },
  {
    id: 'risk_10',
    title: 'Branch Router Firmware Exploit Leading to Network Pivoting',
    assetId: 'asset_branch_routers',
    assetName: 'SD-WAN Edge Branch Routers',
    threatId: 'thr_pass_the_hash',
    threatName: 'Lateral Movement via Stolen NTLM Hashes',
    vulnerabilityId: 'CVE-2024-3400',
    likelihood: 2,
    impact: 4,
    assetCriticality: 3,
    riskScore: 54,
    severity: 'Medium',
    probabilityOfLoss: 0.05,
    financialImpact: 15000000,
    expectedAnnualLoss: 3840000 * 0.03, // ~₹1.2L
    existingControls: ['Static ACLs'],
    recommendedControlId: 'ctrl_network_zero_trust',
    recommendedControlName: 'Zero Trust Network Architecture (ZTNA)',
    residualRiskScore: 20,
  },
  {
    id: 'risk_11',
    title: 'Spear-Phishing of Loan Approval Officers for Wire Interception',
    assetId: 'asset_loan_origination',
    assetName: 'Digital Retail Loan Origination System',
    threatId: 'thr_spear_phish',
    threatName: 'Executive Spear-Phishing & Business Email Compromise',
    vulnerabilityId: 'CVE-2024-38112',
    likelihood: 4,
    impact: 3,
    assetCriticality: 4,
    riskScore: 61,
    severity: 'High',
    probabilityOfLoss: 0.12,
    financialImpact: 8000000,
    expectedAnnualLoss: 3840000 * 0.03, // ~₹1.1L
    existingControls: ['Annual Compliance Quiz'],
    recommendedControlId: 'ctrl_employee_sec',
    recommendedControlName: 'Security Awareness & Phishing Simulation',
    residualRiskScore: 23,
  },
  {
    id: 'risk_12',
    title: 'Database Backup Ransomware Encryption without Offline Copies',
    assetId: 'asset_core_db',
    assetName: 'Core Oracle Exadata Banking Mainframe',
    threatId: 'thr_ransomware',
    threatName: 'Double-Extortion Ransomware Syndicate',
    vulnerabilityId: 'CVE-2024-40711',
    likelihood: 2,
    impact: 5,
    assetCriticality: 5,
    riskScore: 66,
    severity: 'High',
    probabilityOfLoss: 0.04,
    financialImpact: 60000000,
    expectedAnnualLoss: 3840000 * 0.03, // ~₹1.1L
    existingControls: ['Nightly SAN Replication'],
    recommendedControlId: 'ctrl_backup_ransom',
    recommendedControlName: 'Immutable Air-Gapped Backup & Recovery',
    residualRiskScore: 19,
  },
  // Additional 14 risks to exceed 25 required
  {
    id: 'risk_13',
    title: 'JWT Secret Key Leak in Client Application Package',
    assetId: 'asset_api_gateway',
    assetName: 'Core Banking API Gateway',
    threatId: 'thr_api_abuse',
    threatName: 'BOLA / Broken Object Level API Exploitation',
    vulnerabilityId: 'CVE-2024-50021',
    likelihood: 2,
    impact: 5,
    assetCriticality: 5,
    riskScore: 67,
    severity: 'High',
    probabilityOfLoss: 0.05,
    financialImpact: 20000000,
    expectedAnnualLoss: 80000,
    existingControls: ['Manual Code Review'],
    recommendedControlId: 'ctrl_api_sec',
    recommendedControlName: 'API Security & WAAP Shield',
    residualRiskScore: 21,
  },
  {
    id: 'risk_14',
    title: 'Unrestricted Egress Exfiltration of Credit Analytics Lake',
    assetId: 'asset_bi_analytics',
    assetName: 'Enterprise Big Data & Risk Analytics Lake',
    threatId: 'thr_insider_abuse',
    threatName: 'Privileged Staff Unauthorized Customer Record Exfiltration',
    likelihood: 2,
    impact: 4,
    assetCriticality: 4,
    riskScore: 56,
    severity: 'Medium',
    probabilityOfLoss: 0.06,
    financialImpact: 14000000,
    expectedAnnualLoss: 75000,
    existingControls: ['Basic Role Permissions'],
    recommendedControlId: 'ctrl_dlp',
    recommendedControlName: 'Data Loss Prevention & Cryptographic Vaulting',
    residualRiskScore: 22,
  },
  {
    id: 'risk_15',
    title: 'Corporate Email Forwarding Rule Hijack (Exchange BEC)',
    assetId: 'asset_email_collab',
    assetName: 'Corporate Microsoft 365 Cloud Suite',
    threatId: 'thr_spear_phish',
    threatName: 'Executive Spear-Phishing & Business Email Compromise',
    likelihood: 3,
    impact: 3,
    assetCriticality: 3,
    riskScore: 50,
    severity: 'Medium',
    probabilityOfLoss: 0.11,
    financialImpact: 6000000,
    expectedAnnualLoss: 66000,
    existingControls: ['Standard Spam Filter'],
    recommendedControlId: 'ctrl_mfa',
    recommendedControlName: 'FIDO2 Passwordless & Contextual MFA',
    residualRiskScore: 16,
  },
  {
    id: 'risk_16',
    title: 'NPCI Switch Deserialization Flaw in High-Speed Ingestion',
    assetId: 'asset_payment_switch',
    assetName: 'NPCI UPI & IMPS Real-Time Switch',
    threatId: 'thr_zero_day',
    threatName: 'Remote Code Execution in Enterprise Web Frameworks',
    vulnerabilityId: 'CVE-2024-50032',
    likelihood: 1,
    impact: 5,
    assetCriticality: 5,
    riskScore: 58,
    severity: 'Medium',
    probabilityOfLoss: 0.02,
    financialImpact: 35000000,
    expectedAnnualLoss: 70000,
    existingControls: ['Private Leased Line'],
    recommendedControlId: 'ctrl_vuln_mgmt',
    recommendedControlName: 'Vulnerability Management & Risk Prioritization',
    residualRiskScore: 17,
  },
  {
    id: 'risk_17',
    title: 'Unauthenticated File Upload on Vendor Invoicing Portal',
    assetId: 'asset_vendor_portal',
    assetName: 'Third-Party Vendor Procurement & Settlement Portal',
    threatId: 'thr_supply_chain',
    threatName: 'Third-Party Software Dependency Poisoning',
    vulnerabilityId: 'CVE-2024-4577',
    likelihood: 3,
    impact: 3,
    assetCriticality: 3,
    riskScore: 52,
    severity: 'Medium',
    probabilityOfLoss: 0.08,
    financialImpact: 7500000,
    expectedAnnualLoss: 60000,
    existingControls: ['File Extension Whitelist'],
    recommendedControlId: 'ctrl_third_party',
    recommendedControlName: 'Third-Party Risk Management (TPRM)',
    residualRiskScore: 20,
  },
  {
    id: 'risk_18',
    title: 'Kubernetes Pod Escaping to Host Cloud Environment',
    assetId: 'asset_cloud_infra',
    assetName: 'Cloud Production VPC',
    threatId: 'thr_zero_day',
    threatName: 'Remote Code Execution in Enterprise Web Frameworks',
    vulnerabilityId: 'CVE-2024-3094',
    likelihood: 1,
    impact: 5,
    assetCriticality: 5,
    riskScore: 55,
    severity: 'Medium',
    probabilityOfLoss: 0.02,
    financialImpact: 28000000,
    expectedAnnualLoss: 56000,
    existingControls: ['AWS GuardDuty'],
    recommendedControlId: 'ctrl_cloud_sec',
    recommendedControlName: 'Cloud Security Posture (CSPM & CWPP)',
    residualRiskScore: 16,
  },
  {
    id: 'risk_19',
    title: 'SIM Swap Bypass of SMS OTP for Retail High-Value Transfers',
    assetId: 'asset_mobile_bank',
    assetName: 'Mobile Banking (TitanPay)',
    threatId: 'thr_sim_swap',
    threatName: 'Targeted Telecom SIM Swap & OTP Interception',
    likelihood: 3,
    impact: 3,
    assetCriticality: 5,
    riskScore: 59,
    severity: 'Medium',
    probabilityOfLoss: 0.09,
    financialImpact: 6000000,
    expectedAnnualLoss: 54000,
    existingControls: ['Cooling-off Period on New Beneficiaries'],
    recommendedControlId: 'ctrl_mfa',
    recommendedControlName: 'FIDO2 Passwordless & Contextual MFA',
    residualRiskScore: 18,
  },
  {
    id: 'risk_20',
    title: 'Corporate Wi-Fi WPA2 Enterprise EAP-TLS Downgrade',
    assetId: 'asset_branch_routers',
    assetName: 'SD-WAN Edge Branch Routers',
    threatId: 'thr_pass_the_hash',
    threatName: 'Lateral Movement via Stolen NTLM Hashes',
    vulnerabilityId: 'CVE-2024-24919',
    likelihood: 2,
    impact: 3,
    assetCriticality: 3,
    riskScore: 45,
    severity: 'Low',
    probabilityOfLoss: 0.04,
    financialImpact: 5000000,
    expectedAnnualLoss: 20000,
    existingControls: ['Enterprise RADIUS Server'],
    recommendedControlId: 'ctrl_network_zero_trust',
    recommendedControlName: 'Zero Trust Network Architecture (ZTNA)',
    residualRiskScore: 15,
  },
  {
    id: 'risk_21',
    title: 'ATM Operator Physical USB Keyboard Port Tamper',
    assetId: 'asset_atm_network',
    assetName: 'Nationwide ATM Switch & Terminal Fleet',
    threatId: 'thr_atm_malware',
    threatName: 'ATM Black-Box Cash-out & Jackpotting',
    vulnerabilityId: 'CVE-2024-20353',
    likelihood: 2,
    impact: 3,
    assetCriticality: 4,
    riskScore: 48,
    severity: 'Low',
    probabilityOfLoss: 0.03,
    financialImpact: 8000000,
    expectedAnnualLoss: 24000,
    existingControls: ['Physical Cabinet Key Lock'],
    recommendedControlId: 'ctrl_edr',
    recommendedControlName: 'Endpoint Detection & Response (EDR / XDR)',
    residualRiskScore: 17,
  },
  {
    id: 'risk_22',
    title: 'Blind SQL Injection in Digital Lending Credit Bureau Query',
    assetId: 'asset_loan_origination',
    assetName: 'Digital Retail Loan Origination System',
    threatId: 'thr_db_injection',
    threatName: 'Blind SQL Injection in Legacy Reporting Services',
    vulnerabilityId: 'CVE-2024-38856',
    likelihood: 2,
    impact: 4,
    assetCriticality: 4,
    riskScore: 54,
    severity: 'Medium',
    probabilityOfLoss: 0.04,
    financialImpact: 9000000,
    expectedAnnualLoss: 36000,
    existingControls: ['Database Firewall'],
    recommendedControlId: 'ctrl_vuln_mgmt',
    recommendedControlName: 'Vulnerability Management & Risk Prioritization',
    residualRiskScore: 18,
  },
  {
    id: 'risk_23',
    title: 'SIEM Log Storage Retention Exhaustion During Active Incident',
    assetId: 'asset_core_db',
    assetName: 'Core Oracle Exadata Banking Mainframe',
    threatId: 'thr_insider_abuse',
    threatName: 'Privileged Staff Unauthorized Customer Record Exfiltration',
    likelihood: 2,
    impact: 3,
    assetCriticality: 5,
    riskScore: 51,
    severity: 'Medium',
    probabilityOfLoss: 0.04,
    financialImpact: 7000000,
    expectedAnnualLoss: 28000,
    existingControls: ['Local Syslog Disk Alert'],
    recommendedControlId: 'ctrl_siem',
    recommendedControlName: '24/7 Managed SOC & AI Threat Hunting',
    residualRiskScore: 16,
  },
  {
    id: 'risk_24',
    title: 'Layer-7 HTTP Flood Crippling Consumer Web Portal',
    assetId: 'asset_net_bank',
    assetName: 'Internet Banking Web Portal',
    threatId: 'thr_ddos_banking',
    threatName: 'Volumetric L7 DDoS on Mobile & Web Endpoints',
    likelihood: 3,
    impact: 3,
    assetCriticality: 5,
    riskScore: 57,
    severity: 'Medium',
    probabilityOfLoss: 0.08,
    financialImpact: 4500000,
    expectedAnnualLoss: 36000,
    existingControls: ['ISP Bandwidth Throttling'],
    recommendedControlId: 'ctrl_api_sec',
    recommendedControlName: 'API Security & WAAP Shield',
    residualRiskScore: 19,
  },
  {
    id: 'risk_25',
    title: 'Cloud AWS S3 Archive Snapshot Permission Drift',
    assetId: 'asset_cloud_infra',
    assetName: 'Cloud Production VPC',
    threatId: 'thr_cloud_misconfig',
    threatName: 'Cloud Storage & IAM Permission Misconfiguration',
    vulnerabilityId: 'CVE-2024-50030',
    likelihood: 2,
    impact: 3,
    assetCriticality: 4,
    riskScore: 46,
    severity: 'Low',
    probabilityOfLoss: 0.05,
    financialImpact: 5000000,
    expectedAnnualLoss: 25000,
    existingControls: ['Manual Monthly AWS Audits'],
    recommendedControlId: 'ctrl_cloud_sec',
    recommendedControlName: 'Cloud Security Posture (CSPM & CWPP)',
    residualRiskScore: 15,
  },
  {
    id: 'risk_26',
    title: 'USB Mass Storage Device Attachment by Contract Staff',
    assetId: 'asset_employee_endpoints',
    assetName: 'Corporate Employee Fleet',
    threatId: 'thr_insider_abuse',
    threatName: 'Privileged Staff Unauthorized Customer Record Exfiltration',
    vulnerabilityId: 'CVE-2024-26169',
    likelihood: 3,
    impact: 3,
    assetCriticality: 3,
    riskScore: 47,
    severity: 'Low',
    probabilityOfLoss: 0.06,
    financialImpact: 4000000,
    expectedAnnualLoss: 24000,
    existingControls: ['Group Policy Object (GPO)'],
    recommendedControlId: 'ctrl_dlp',
    recommendedControlName: 'Data Loss Prevention & Cryptographic Vaulting',
    residualRiskScore: 14,
  },
];

// Verify and normalize baseline total EAL to exact benchmark ₹38.4L
const rawEALSum = SEED_RISKS.reduce((acc, r) => acc + r.expectedAnnualLoss, 0);
if (rawEALSum > 0) {
  const scale = 3840000 / rawEALSum;
  SEED_RISKS.forEach((r) => {
    r.expectedAnnualLoss = Math.round(r.expectedAnnualLoss * scale);
  });
}

// ==========================================
// 6. HISTORICAL SNAPSHOTS (90 Days)
// ==========================================
export const SEED_HISTORY: RiskSnapshot[] = [
  { date: '90d ago', riskScore: 81, eal: 47.8, activeVulnerabilities: 48, criticalThreatCount: 6 },
  { date: '75d ago', riskScore: 78, eal: 45.2, activeVulnerabilities: 44, criticalThreatCount: 6 },
  { date: '60d ago', riskScore: 76, eal: 43.1, activeVulnerabilities: 41, criticalThreatCount: 5 },
  { date: '45d ago', riskScore: 73, eal: 41.5, activeVulnerabilities: 38, criticalThreatCount: 5 },
  { date: '30d ago', riskScore: 71, eal: 40.2, activeVulnerabilities: 35, criticalThreatCount: 4 },
  { date: '15d ago', riskScore: 69, eal: 39.1, activeVulnerabilities: 32, criticalThreatCount: 4 },
  { date: 'Current', riskScore: 68, eal: 38.4, activeVulnerabilities: 30, criticalThreatCount: 4 },
];

// ==========================================
// 7. COMPLIANCE MAPPINGS
// ==========================================
export const SEED_COMPLIANCE: ComplianceControl[] = [
  {
    id: 'comp_01',
    controlName: 'Multi-Factor Authentication for Privileged Access',
    category: 'Identity & Access Control',
    nistId: 'PR.AC-7',
    nistStatus: 'Implemented',
    isoId: 'A.9.4.2',
    isoStatus: 'Partial',
    rbiId: 'Sec 3.3 (Mandatory 2FA)',
    rbiStatus: 'Implemented',
    associatedControlId: 'ctrl_mfa',
    gapSummary: 'ISO requires FIDO2 hardware tokens across all DR personnel; partial implementation pending.',
    riskLevel: 'High',
  },
  {
    id: 'comp_02',
    controlName: 'API Gateway Runtime Authorization & Rate Limiting',
    category: 'Application Security',
    nistId: 'PR.PT-3',
    nistStatus: 'Partial',
    isoId: 'A.8.26',
    isoStatus: 'Partial',
    rbiId: 'Sec 4.2 (API Governance)',
    rbiStatus: 'Partial',
    associatedControlId: 'ctrl_api_sec',
    gapSummary: 'RBI mandates strict token lifecycle validation; partner APIs currently lack automated BOLA controls.',
    riskLevel: 'Critical',
  },
  {
    id: 'comp_03',
    controlName: 'Continuous Endpoint Detection & Isolation',
    category: 'Endpoint Security',
    nistId: 'DE.CM-4',
    nistStatus: 'Implemented',
    isoId: 'A.8.7',
    isoStatus: 'Implemented',
    rbiId: 'Sec 5.1 (Endpoint Hardening)',
    rbiStatus: 'Implemented',
    associatedControlId: 'ctrl_edr',
    gapSummary: 'Fully compliant with RBI directive on 24/7 endpoint telemetry and USB control.',
    riskLevel: 'Low',
  },
  {
    id: 'comp_04',
    controlName: 'Cloud Infrastructure Baseline Configuration & Drift Detection',
    category: 'Cloud Governance',
    nistId: 'PR.IP-1',
    nistStatus: 'Partial',
    isoId: 'A.8.8',
    isoStatus: 'Implemented',
    rbiId: 'Sec 6.3 (Cloud Architecture)',
    rbiStatus: 'Partial',
    associatedControlId: 'ctrl_cloud_sec',
    gapSummary: 'Automated CI/CD security gating required before deploying microservices into AWS VPC.',
    riskLevel: 'High',
  },
  {
    id: 'comp_05',
    controlName: 'Third-Party Vendor Continuous Risk Auditing',
    category: 'Supply Chain Risk',
    nistId: 'ID.SC-1',
    nistStatus: 'Partial',
    isoId: 'A.15.1',
    isoStatus: 'Partial',
    rbiId: 'Sec 7.2 (Vendor Oversight)',
    rbiStatus: 'Partial',
    associatedControlId: 'ctrl_third_party',
    gapSummary: 'Annual questionnaire insufficient under revised RBI Master Direction; real-time telemetry required.',
    riskLevel: 'High',
  },
  {
    id: 'comp_06',
    controlName: 'Air-Gapped Immutable Ransomware Data Backups',
    category: 'Business Resilience',
    nistId: 'RC.RP-1',
    nistStatus: 'Implemented',
    isoId: 'A.8.14',
    isoStatus: 'Implemented',
    rbiId: 'Sec 9.2 (BCP & DR Drills)',
    rbiStatus: 'Implemented',
    associatedControlId: 'ctrl_backup_ransom',
    gapSummary: 'Quarterly failover drill tested with sub-2-hour RTO on Oracle Exadata.',
    riskLevel: 'Low',
  },
  {
    id: 'comp_07',
    controlName: 'Data Loss Prevention (DLP) for Customer PII',
    category: 'Data Protection',
    nistId: 'PR.DS-1',
    nistStatus: 'Partial',
    isoId: 'A.8.24',
    isoStatus: 'Partial',
    rbiId: 'Sec 4.1 (Customer Confidentiality)',
    rbiStatus: 'Partial',
    associatedControlId: 'ctrl_dlp',
    gapSummary: 'PII masking incomplete across legacy offline test environments.',
    riskLevel: 'Medium',
  },
];

// ==========================================
// 8. WHAT-IF SCENARIOS (5 Pre-configured)
// ==========================================
export const SEED_SCENARIOS: Scenario[] = [
  {
    id: 'scen_01',
    name: 'Shift ₹3L from EDR to API Security',
    description: 'Reallocates capital from saturated endpoint detection into our highest financial exposure vector (API Gateway).',
    badge: 'Strategic Rebalancing',
    budget: 1000000,
    controlAllocations: {
      ctrl_api_sec: 450000, // +₹3L
      ctrl_edr: 50000, // -₹1.5L
      ctrl_iam: 150000,
      ctrl_cloud_sec: 150000,
      ctrl_vuln_mgmt: 100000,
      ctrl_mfa: 50000,
      ctrl_employee_sec: 25000,
      ctrl_third_party: 25000,
    },
    threatMultiplier: 1.0,
    criticalityWeight: 1.0,
    projectedRiskScore: 49,
    projectedEAL: 2410000,
    riskReductionPct: 37.2,
    lossAvoided: 1430000,
    rosi: 2.4,
  },
  {
    id: 'scen_02',
    name: 'Ransomware Surge & Zero-Day Wave',
    description: 'Models a 35% spike in external threat campaign frequency targeting branch networks and cloud endpoints.',
    badge: 'Adversarial Stress Test',
    budget: 1000000,
    controlAllocations: {
      ctrl_api_sec: 200000,
      ctrl_edr: 300000,
      ctrl_backup_ransom: 200000,
      ctrl_iam: 150000,
      ctrl_cloud_sec: 150000,
    },
    threatMultiplier: 1.35,
    criticalityWeight: 1.0,
    projectedRiskScore: 62,
    projectedEAL: 3120000,
    riskReductionPct: 24.5,
    lossAvoided: 980000,
    rosi: 2.0,
  },
  {
    id: 'scen_03',
    name: 'Budget Expansion to ₹15 Lakhs (+50%)',
    description: 'Tests risk reduction yield if board approves a ₹5L supplemental mid-year cybersecurity allocation.',
    badge: 'Capital Expansion',
    budget: 1500000,
    controlAllocations: {
      ctrl_api_sec: 450000,
      ctrl_iam: 250000,
      ctrl_cloud_sec: 250000,
      ctrl_edr: 200000,
      ctrl_vuln_mgmt: 150000,
      ctrl_mfa: 100000,
      ctrl_third_party: 100000,
    },
    threatMultiplier: 1.0,
    criticalityWeight: 1.0,
    projectedRiskScore: 34,
    projectedEAL: 1680000,
    riskReductionPct: 56.2,
    lossAvoided: 2160000,
    rosi: 2.8,
  },
  {
    id: 'scen_04',
    name: 'Budget Reduction to ₹7 Lakhs (-30% Fiscal Constraint)',
    description: 'Simulates austerity conditions to pinpoint essential non-negotiable security controls.',
    badge: 'Austerity Mode',
    budget: 700000,
    controlAllocations: {
      ctrl_api_sec: 250000,
      ctrl_iam: 150000,
      ctrl_cloud_sec: 120000,
      ctrl_edr: 100000,
      ctrl_vuln_mgmt: 80000,
    },
    threatMultiplier: 1.0,
    criticalityWeight: 1.0,
    projectedRiskScore: 54,
    projectedEAL: 2850000,
    riskReductionPct: 25.8,
    lossAvoided: 990000,
    rosi: 2.3,
  },
  {
    id: 'scen_05',
    name: 'RBI Audit Enforcement on Identity & Supply Chain',
    description: 'Allocates heavy priority towards regulatory compliance gaps in PAM, MFA, and Vendor Risk.',
    badge: 'Regulatory Mandate',
    budget: 1000000,
    controlAllocations: {
      ctrl_iam: 300000,
      ctrl_mfa: 150000,
      ctrl_third_party: 200000,
      ctrl_api_sec: 200000,
      ctrl_cloud_sec: 150000,
    },
    threatMultiplier: 1.0,
    criticalityWeight: 1.15,
    projectedRiskScore: 45,
    projectedEAL: 2320000,
    riskReductionPct: 39.5,
    lossAvoided: 1520000,
    rosi: 2.5,
  },
];
